name: Bot Cripto Final

on:
  schedule:
    # CORRECCIÓN DE HORARIO:
    # '1-23/2' = Horas IMPARES UTC (1, 3, 5, ... 19, 21, 23)
    # 21:00 UTC = 22:00 España (Tu tweet de las 10 PM)
    # ',14' = Añadimos las 14:00 UTC explícitamente para el reporte de las 15:00
    - cron: '17 1-23/2,14 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar librerías
        run: pip install -r requirements.txt
      - name: Ejecutar Bot
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python main.py
